apiVersion: v1
kind: Pod
metadata:
  name: node-app-manual-v2
  labels:
    creation: manual
    env: prod
spec:
  containers:
  - image: tengsun/node-app
    name: node-app
    ports:
    - containerPort: 1234
      protocol: TCP