apiVersion: v1
kind: ReplicationController
metadata:
  name: node-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: tengsun/node-app
        ports:
        - containerPort: 1234
